.TH EDGAR 6 "October 2015" "edgar" "The Legend of Edgar"

.SH NAME
edgar - A 2D platform game with a persistent world.

.SH SYNOPSIS
.B edgar
[\fIOPTION\fR]

.SH DESCRIPTION
The Legend of Edgar is a platform game, not unlike those found on the Amiga
and SNES. Edgar must battle his way across the world, solving puzzles and
defeating powerful enemies to achieve his quest.

When Edgar's father fails to return home after venturing out one dark and
stormy night, Edgar fears the worst: he has been captured by the evil
sorcerer who lives in a fortress beyond the forbidden swamp.

Donning his armour, Edgar sets off to rescue him, but his quest will not be
easy...

.SH OPTIONS

.TP
.BI \-record\  filename
Captures keyboard input.

.TP
.BI \-playback\  filename
Replays captured keyboard input.

.TP
.BI \-load\  slot
Loads the game in \fIslot\fR. Slots begin at 0.

.TP
.B -nojoystick
Disables the joystick.

.TP
.BI \-joystick\  slot
Use the joystick in slot \fIslot\fR. Slots begin at 0.

.TP
.B -showcredits
Show the end credits.

.TP
.BI \-language\  language
Use language code \fIlanguage\fR. e.g. en_US, es, pl

.TP
.BR \-h ", " \-help
Display help screen.

.SH MORE INFO
The Legend of Edgar gameplay manual can be found in
</usr/share/doc/edgar/index.html>.

.SH AUTHOR
Written by Richard Sweeney <riksweeney@hotmail.com>.
