void loadMap(char *);
void saveMap(void);
void doMap(void);
void drawMap(int);
void centerEntityOnMap(void);
void freeMap(void);
SDL_Surface *tileImage(int);
SDL_Surface *mapImageAt(int, int);
int mapTileAt(int, int);
int maxMapX(void);
int maxMapY(void);
void setMaxMapX(int);
void setMaxMapY(int);
void setMinMapX(int);
void setMinMapY(int);
int getMinMapX(void);
int getMinMapY(void);
int mapStartX(void);
int mapStartY(void);
void mapStartXNext(int);
void mapStartYNext(int);
void setTileAt(int, int, int);
int nextTile(int);
int prevTile(int);
void centerMapOnEntity(Entity *);
int getMapStartX(void);
int getMapStartY(void);
void setMapStartX(int);
void setMapStartY(int);
