void freeDecorations(void);
Entity *getFreeDecoration(void);
void doDecorations(void);
void drawDecorations(void);
void addStarExplosion(int, int);
void addSparkle(int, int);
Entity *addTrail(int, int, char *, int);
Entity *addDecoration(char *, int, int);
Entity *addSmoke(int, int, char *);
Entity *addMultipleSparkles(int, int, char *);
void addDecorationFromScript(char *);
void addBlood(int, int);
Entity *addBasicDecoration(int, int, char *);
