void initGame(void);
void doGame(void);
void drawGame(void);
void shakeScreen(int, int);
void setTransition(int, void (*)(void));
void setNextLevel(char *, char *);
void goToNextMap(void);
void setCheckpoint(float, float);
void getCheckpoint(float *, float *);
void pauseGame(void);
